"""Add ledger models and UserProfile

Revision ID: 774f440cf2aa
Revises: 0002_eth_custodial_constraints
Create Date: 2026-05-09 18:51:48.809851

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "774f440cf2aa"
down_revision: str | None = "0002_eth_custodial_constraints"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_assets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("network", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("decimals", sa.Integer(), server_default=sa.text("2"), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asset_class IN ('fiat', 'stablecoin', 'crypto', 'equity', 'etf', 'bond', 'treasury', 'roboadvisor_share')",
            name="chk_canonical_assets_class",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "asset_class", "network", name="uq_canonical_assets_symbol_class_network"),
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_dirty", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_recomputed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "summaries",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "risk_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "portfolio_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "canonical_accounts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("account_kind", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "account_kind IN ('checking', 'investment', 'roboadvisor', 'wallet_address', 'card', 'savings')",
            name="chk_canonical_accounts_kind",
        ),
        sa.ForeignKeyConstraint(["connection_id"], ["provider_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "external_id", name="uq_canonical_accounts_connection_external"),
    )
    op.create_index(op.f("ix_canonical_accounts_user_id"), "canonical_accounts", ["user_id"], unique=False)
    op.create_table(
        "canonical_balances",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("avg_cost_usd", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("cost_basis_usd", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("as_of", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name="chk_canonical_balances_quantity_nonneg"),
        sa.ForeignKeyConstraint(["account_id"], ["canonical_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asset_id"], ["canonical_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "asset_id", name="uq_canonical_balances_account_asset"),
    )
    op.create_index(op.f("ix_canonical_balances_asset_id"), "canonical_balances", ["asset_id"], unique=False)
    op.create_index(op.f("ix_canonical_balances_user_id"), "canonical_balances", ["user_id"], unique=False)
    op.create_table(
        "canonical_transactions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=True),
        sa.Column("source_account_id", sa.UUID(), nullable=True),
        sa.Column("dest_account_id", sa.UUID(), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("source_amount", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("source_currency", sa.String(), nullable=True),
        sa.Column("dest_amount", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("dest_unit", sa.String(), nullable=True),
        sa.Column(
            "fee_amount",
            sa.Numeric(precision=28, scale=10),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("fee_currency", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default=sa.text("'completed'"), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("raw_provider_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "classifier",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_kind", sa.String(), nullable=False),
        sa.Column("source_plan_step_id", sa.UUID(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("merchant", sa.String(), nullable=True),
        sa.Column("search_text", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IS NULL OR direction IN ('in', 'out', 'internal')",
            name="chk_canonical_transactions_direction",
        ),
        sa.CheckConstraint(
            "source_kind IN ('provider_pulled', 'document_ingested', 'agent_issued')",
            name="chk_canonical_transactions_source_kind",
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'pending', 'failed', 'cancelled')",
            name="chk_canonical_transactions_status",
        ),
        sa.CheckConstraint(
            "type IN ('trade', 'transfer_internal', 'external_in', 'external_out', 'fee', 'dividend', 'classifier_change', 'onchain', 'other')",
            name="chk_canonical_transactions_type",
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["canonical_assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["connection_id"], ["provider_connections.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dest_account_id"], ["canonical_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_account_id"], ["canonical_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "external_id", name="uq_canonical_transactions_connection_external"),
    )
    op.create_index(
        op.f("ix_canonical_transactions_source_document_id"),
        "canonical_transactions",
        ["source_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_transactions_source_plan_step_id"),
        "canonical_transactions",
        ["source_plan_step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_transactions_user_id"),
        "canonical_transactions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_canonical_transactions_user_id"), table_name="canonical_transactions")
    op.drop_index(op.f("ix_canonical_transactions_source_plan_step_id"), table_name="canonical_transactions")
    op.drop_index(op.f("ix_canonical_transactions_source_document_id"), table_name="canonical_transactions")
    op.drop_table("canonical_transactions")
    op.drop_index(op.f("ix_canonical_balances_user_id"), table_name="canonical_balances")
    op.drop_index(op.f("ix_canonical_balances_asset_id"), table_name="canonical_balances")
    op.drop_table("canonical_balances")
    op.drop_index(op.f("ix_canonical_accounts_user_id"), table_name="canonical_accounts")
    op.drop_table("canonical_accounts")
    op.drop_table("user_profiles")
    op.drop_table("canonical_assets")
    # ### end Alembic commands ###
